export default [
  {
    id: 0,
    category: 'Addition',
    questionText: 'What is 2 + 9?',
    answerKey: 'a',
    options: {
      a: 11,
      b: 7,
      c: 18,
      d: 29,
      e: 'Not possible',
    },
    timer: 5,
    difficulty: 1,
  },
  {
    id: 1,
    category: 'Subtraction',
    questionText: 'What is 12 - 4?',
    answerKey: 'c',
    options: {
      a: 12,
      b: -8,
      c: 8,
      d: 16,
      e: 'Not possible',
    },
    timer: 5,
    difficulty: 1,
  },
  {
    id: 2,
    category: 'Subtraction',
    questionText: 'What is 10 - 22?',
    answerKey: 'b',
    options: {
      a: 32,
      b: -12,
      c: -22,
      d: 10,
      e: 'Not possible',
    },
    timer: 5,
    difficulty: 1,
  },
  {
    id: 3,
    category: 'Multiplication',
    questionText: 'What is 5 * 12?',
    answerKey: 'a',
    options: {
      a: 60,
      b: 17,
      c: 15,
      d: 7,
      e: 'Not possible',
    },
    timer: 10,
    difficulty: 2,
  },
  {
    id: 4,
    category: 'Multiplication',
    questionText: 'What is 11 * 4?',
    answerKey: 'c',
    options: {
      a: 11,
      b: 15,
      c: 44,
      d: 7,
      e: 'Not possible',
    },
    timer: 10,
    difficulty: 2,
  },
  {
    id: 5,
    category: 'Division',
    questionText: 'What is 9 / 3?',
    answerKey: 'd',
    options: {
      a: 6,
      b: 12,
      c: 18,
      d: 3,
      e: 'Not possible',
    },
    timer: 10,
    difficulty: 2,
  },
  {
    id: 6,
    category: 'Division',
    questionText: 'What is 9 / 0?',
    answerKey: 'e',
    options: {
      a: 0,
      b: 9,
      c: 90,
      d: 12,
      e: 'Not possible',
    },
    timer: 15,
    difficulty: 3,
  },
];
